### ISSUE TITLE
Why this url configuration cannot be imported?

### ISSUE THREAD

**Issue by xmh0511** [LibNyanpasu/clash-nyanpasu#255]
### 复现步骤 / Step to reproduce

https://api.v1.mk/sub?target=clash&url=https%3A%2F%2Fclashgithub.com%2Fwp-content%2Fuploads%2Frss%2F20240111.yml&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true

This configuration can successfully be recognized by `clash_for_windows` and be imported correctly. However, `clash-nyanpasu` cannot import it.

### 预期行为 / Expected behaviour

Should be successfully import the valid configuration from the URL

### 实际行为 / Actual Behaviour

There is no react

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

macOs12

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Hello.&nbsp;
This Profile URL, tested in latest nightly build, works &nbsp;as expected. Could you &nbsp;enable &nbsp;tracing level &nbsp;in app log where you can find at Miscellaneous Settings tabs, and provide &nbsp;us with the logs?


------------------ Original ------------------
From: xmh0511 ***@***.***&gt;
Date: Thu, Jan 11, 2024 1:46 PM
To: keiko233/clash-nyanpasu ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [keiko233/clash-nyanpasu] Why this url configuration cannot be imported? (Issue #255)





 
复现步骤 / Step to reproduce
 
https://api.v1.mk/sub?target=clash&amp;url=https%3A%2F%2Fclashgithub.com%2Fwp-content%2Fuploads%2Frss%2F20240111.yml&amp;insert=false&amp;config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&amp;emoji=true&amp;list=false&amp;xudp=false&amp;udp=false&amp;tfo=false&amp;expand=true&amp;scv=false&amp;fdn=false&amp;new_name=true
 
This configuration can successfully be recognized by clash_for_windows and be imported correctly. However, clash-nyanpasu cannot import it.
 
预期行为 / Expected behaviour
 
Should be successfully import the valid configuration from the URL
 
实际行为 / Actual Behaviour
 
There is no react
 
应用日志 / App logs
 
No response
 
备注 / Addition details
 
No response
 
Clash Nyapasu 版本号 / Clash Nyapasu
 
1.4.1
 
是否为 Pre-release / Is pre-release version
 
no
 
操作系统及版本 / OS version
 
macOs12
 
自查步骤 / Verify steps
  
 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request 

 您已仔细查看并知情 Q&amp;A 中的内容 / You have checked Q&amp;A carefully 

 您已搜索过 Issue Tracker，没有找到类似内容 / I have searched on Issue Tracker, No duplicate or related open issue has been found 

 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs 

 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version
